

import React, { useState, useEffect } from 'react';
import { Course, ReelData } from '../types';

interface ClassroomViewProps {
  course: Course;
  onBack: () => void;
  onOpenReel: (index: number) => void;
  onStartExam: () => void;
  onToggleTheme: () => void;
  currentTheme: 'light' | 'dark';
}

const ClassroomView: React.FC<ClassroomViewProps> = ({ course, onBack, onOpenReel, onStartExam, onToggleTheme, currentTheme }) => {
  const [activeTab, setActiveTab] = useState<'CURRICULUM' | 'EXAM' | 'NOTES'>('CURRICULUM');

  // Calculate stats
  const completedCount = course.reels.filter(r => r.userQuizResult === true).length;
  const progress = Math.round((completedCount / course.totalReels) * 100);

  // Render Math formulas if they exist
  useEffect(() => {
    // @ts-ignore
    if (window.renderMathInElement) {
        // @ts-ignore
        window.renderMathInElement(document.body, {
            delimiters: [
                {left: '$$', right: '$$', display: true},
                {left: '$', right: '$', display: false},
            ],
            throwOnError: false
        });
    }
  }, [activeTab]);

  const handleDownloadPDF = () => {
    const printContent = `
      <html>
        <head>
          <title>${course.title} - Notes</title>
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #1c1917; line-height: 1.6; }
            h1 { border-bottom: 2px solid #ea580c; padding-bottom: 10px; color: #ea580c; font-size: 24px; }
            .meta { font-size: 12px; color: #78716c; margin-bottom: 40px; }
            .module { margin-bottom: 30px; border: 1px solid #e7e5e4; padding: 20px; border-radius: 8px; page-break-inside: avoid; }
            .module-title { font-weight: bold; font-size: 16px; margin-bottom: 10px; display: flex; align-items: center; gap: 10px; }
            .index { background: #ea580c; color: white; width: 24px; height: 24px; display: inline-flex; align-items: center; justify-content: center; border-radius: 50%; font-size: 12px; }
            .concept-box { background: #fff7ed; border-left: 4px solid #ea580c; padding: 10px; margin-bottom: 10px; font-style: italic; }
            ul { margin: 0; padding-left: 20px; }
            li { margin-bottom: 5px; font-size: 14px; }
          </style>
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
          <script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"></script>
        </head>
        <body>
          <h1>${course.title}</h1>
          <div class="meta">Generated by Orbis AI • ${new Date().toLocaleDateString()}</div>
          ${course.reels.map((reel, idx) => `
            <div class="module">
              <div class="module-title">
                 <span class="index">${idx + 1}</span> ${reel.title}
              </div>
              ${reel.keyConcept ? `<div class="concept-box"><strong>Core Concept:</strong> ${reel.keyConcept}</div>` : ''}
              ${reel.bulletPoints && reel.bulletPoints.length > 0 ? 
                `<ul>${reel.bulletPoints.map(bp => `<li>${bp}</li>`).join('')}</ul>` 
                : '<p style="font-size: 12px; color: #999;">No specific notes recorded.</p>'}
            </div>
          `).join('')}
          <script>
            document.addEventListener("DOMContentLoaded", function() {
                renderMathInElement(document.body, {
                    delimiters: [
                      {left: '$$', right: '$$', display: true},
                      {left: '$', right: '$', display: false},
                    ],
                    throwOnError: false
                });
                setTimeout(() => window.print(), 1000);
            });
          </script>
        </body>
      </html>
    `;
    
    const printWindow = window.open('', '_blank');
    if (printWindow) {
        printWindow.document.write(printContent);
        printWindow.document.close();
    }
  };

  return (
    <div className="h-[100dvh] w-full bg-[#fafaf9] dark:bg-[#0c0a09] font-sans flex flex-col transition-colors duration-500 overflow-hidden">
      
      {/* Header */}
      <div className="px-6 py-4 md:px-8 md:py-6 border-b border-stone-200 dark:border-stone-800 bg-white dark:bg-stone-900 shrink-0 z-20 flex justify-between items-center">
         <div className="flex items-center gap-4">
             <button onClick={onBack} className="w-8 h-8 md:w-10 md:h-10 rounded-full bg-stone-100 dark:bg-stone-800 flex items-center justify-center text-stone-500 hover:text-orange-600 transition-colors">
                 <span className="material-symbols-outlined text-lg">arrow_back</span>
             </button>
             <div>
                 <span className="text-[10px] font-bold text-orange-600 uppercase tracking-widest block mb-1">Classroom</span>
                 <h1 className="text-lg md:text-xl font-bold text-stone-900 dark:text-white font-display line-clamp-1">{course.title}</h1>
             </div>
         </div>
         <div className="flex items-center gap-4">
            <div className="hidden md:flex flex-col items-end mr-4">
                <span className="text-[10px] font-bold text-stone-400 uppercase tracking-widest">Mastery</span>
                <span className="text-lg font-bold text-stone-900 dark:text-white">{progress}%</span>
            </div>
            <button onClick={onToggleTheme} className="text-stone-400 hover:text-stone-900 dark:hover:text-white transition-colors">
                <span className="material-symbols-outlined">{currentTheme === 'dark' ? 'light_mode' : 'dark_mode'}</span>
            </button>
         </div>
      </div>

      {/* Main Layout */}
      <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
          
          {/* Sidebar / Tabs */}
          <div className="w-full md:w-64 bg-white dark:bg-stone-900 border-b md:border-b-0 md:border-r border-stone-200 dark:border-stone-800 shrink-0 flex md:flex-col justify-between md:justify-start">
               <div className="p-4 md:p-6 space-y-1 md:space-y-4 flex md:flex-col gap-2 md:gap-0 w-full overflow-x-auto md:overflow-visible">
                   <button 
                      onClick={() => setActiveTab('CURRICULUM')}
                      className={`flex-1 md:w-full text-left px-4 py-3 rounded-lg flex items-center gap-3 transition-colors shrink-0 ${
                          activeTab === 'CURRICULUM' 
                          ? 'bg-orange-50 dark:bg-orange-900/20 text-orange-700 dark:text-orange-400 font-bold' 
                          : 'text-stone-500 hover:bg-stone-50 dark:hover:bg-stone-800'
                      }`}
                   >
                       <span className="material-symbols-outlined">view_agenda</span>
                       <span className="text-xs uppercase tracking-widest">Curriculum</span>
                   </button>
                   
                   <button 
                      onClick={() => setActiveTab('NOTES')}
                      className={`flex-1 md:w-full text-left px-4 py-3 rounded-lg flex items-center gap-3 transition-colors shrink-0 ${
                          activeTab === 'NOTES' 
                          ? 'bg-orange-50 dark:bg-orange-900/20 text-orange-700 dark:text-orange-400 font-bold' 
                          : 'text-stone-500 hover:bg-stone-50 dark:hover:bg-stone-800'
                      }`}
                   >
                       <span className="material-symbols-outlined">sticky_note_2</span>
                       <span className="text-xs uppercase tracking-widest">Notes & Refs</span>
                   </button>

                   <button 
                      onClick={() => setActiveTab('EXAM')}
                      className={`flex-1 md:w-full text-left px-4 py-3 rounded-lg flex items-center gap-3 transition-colors shrink-0 ${
                          activeTab === 'EXAM' 
                          ? 'bg-orange-50 dark:bg-orange-900/20 text-orange-700 dark:text-orange-400 font-bold' 
                          : 'text-stone-500 hover:bg-stone-50 dark:hover:bg-stone-800'
                      }`}
                   >
                       <span className="material-symbols-outlined">quiz</span>
                       <span className="text-xs uppercase tracking-widest">Exam Room</span>
                   </button>
               </div>
               
               <div className="hidden md:block p-6 border-t border-stone-100 dark:border-stone-800">
                    <div className="p-4 bg-stone-50 dark:bg-stone-800/50 rounded-xl border border-stone-200 dark:border-stone-700">
                         <h4 className="text-[10px] font-bold text-stone-400 uppercase tracking-widest mb-2">Next Milestone</h4>
                         <p className="text-sm font-bold text-stone-900 dark:text-white mb-3">Complete Module {Math.min(completedCount + 1, course.totalReels)}</p>
                         <div className="w-full h-1.5 bg-stone-200 dark:bg-stone-700 rounded-full overflow-hidden">
                             <div className="h-full bg-orange-600 rounded-full" style={{ width: `${progress}%` }}></div>
                         </div>
                    </div>
               </div>
          </div>

          {/* Content Area */}
          <div className="flex-1 bg-stone-50 dark:bg-stone-950 overflow-y-auto p-4 md:p-8 custom-scrollbar">
              <div className="max-w-4xl mx-auto pb-20 md:pb-0">
                  
                  {activeTab === 'CURRICULUM' && (
                      <div className="space-y-6">
                           <div className="mb-6">
                               <h2 className="text-2xl font-bold text-stone-900 dark:text-white font-display mb-2">Learning Modules</h2>
                               <p className="text-sm text-stone-500 dark:text-stone-400">Master these topics to complete the course.</p>
                           </div>
                           
                           <div className="grid gap-4">
                               {course.reels.map((reel, index) => (
                                   <div key={reel.id} className="bg-white dark:bg-stone-900 border border-stone-200 dark:border-stone-800 rounded-xl p-4 md:p-6 shadow-sm hover:border-orange-500/50 transition-colors group">
                                       <div className="flex flex-col md:flex-row gap-4 md:items-start">
                                           {/* Thumbnail / Status */}
                                           <div className="w-full md:w-48 aspect-video bg-stone-100 dark:bg-stone-950 rounded-lg overflow-hidden relative shrink-0">
                                               {reel.imageUri ? (
                                                   <img src={reel.imageUri} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                                               ) : (
                                                   <div className="flex items-center justify-center h-full text-stone-300">
                                                       <span className="material-symbols-outlined text-4xl">play_circle</span>
                                                   </div>
                                               )}
                                               {reel.userQuizResult && (
                                                   <div className="absolute top-2 right-2 w-6 h-6 bg-green-500 text-white rounded-full flex items-center justify-center shadow-md">
                                                       <span className="material-symbols-outlined text-sm">check</span>
                                                   </div>
                                               )}
                                           </div>

                                           {/* Content Info */}
                                           <div className="flex-1">
                                               <div className="flex justify-between items-start mb-2">
                                                    <span className="text-[10px] font-bold text-stone-400 uppercase tracking-widest">Module {index + 1}</span>
                                                    {reel.isProcessing && <span className="text-[10px] font-bold text-orange-600 uppercase tracking-widest animate-pulse">Building...</span>}
                                               </div>
                                               <h3 className="text-lg font-bold text-stone-900 dark:text-white mb-2 leading-tight">{reel.title}</h3>
                                               <p className="text-xs text-stone-500 dark:text-stone-400 line-clamp-2 mb-4">{reel.script?.substring(0, 120)}...</p>
                                               
                                               {/* Actions */}
                                               <div className="flex flex-wrap gap-2">
                                                   <button 
                                                      onClick={() => onOpenReel(index)}
                                                      className="px-4 py-2 bg-stone-900 dark:bg-white text-white dark:text-stone-900 rounded-full font-bold uppercase tracking-widest text-[10px] hover:bg-orange-600 dark:hover:bg-orange-500 hover:text-white dark:hover:text-white transition-colors flex items-center gap-2"
                                                   >
                                                       <span className="material-symbols-outlined text-sm">play_arrow</span>
                                                       Watch Reel
                                                   </button>
                                                   
                                                   {(reel.youtubeQueries || reel.youtubeQuery) && (
                                                        <button 
                                                            onClick={() => window.open(`https://www.youtube.com/results?search_query=${encodeURIComponent(reel.youtubeQuery || reel.title)}`, '_blank')}
                                                            className="px-4 py-2 border border-stone-200 dark:border-stone-800 text-stone-600 dark:text-stone-300 rounded-full font-bold uppercase tracking-widest text-[10px] hover:border-red-500 hover:text-red-500 transition-colors flex items-center gap-2"
                                                        >
                                                            <span className="material-symbols-outlined text-sm">smart_display</span>
                                                            Deep Dive
                                                        </button>
                                                   )}
                                               </div>
                                           </div>
                                       </div>
                                   </div>
                               ))}
                           </div>
                      </div>
                  )}

                  {activeTab === 'NOTES' && (
                      <div className="space-y-6 animate-fade-in">
                          <div className="flex justify-between items-start mb-6">
                               <div>
                                   <h2 className="text-2xl font-bold text-stone-900 dark:text-white font-display mb-2">Smart Notes & Refs</h2>
                                   <p className="text-sm text-stone-500 dark:text-stone-400">Aggregated insights from all modules.</p>
                               </div>
                               <button 
                                  onClick={handleDownloadPDF}
                                  className="px-5 py-2.5 bg-stone-900 dark:bg-white text-white dark:text-stone-900 rounded-lg font-bold uppercase tracking-widest text-xs shadow-md hover:shadow-lg transition-all flex items-center gap-2"
                               >
                                  <span className="material-symbols-outlined text-sm">download</span>
                                  Download PDF
                               </button>
                           </div>

                           <div className="grid gap-6">
                               {course.reels.map((reel, idx) => (
                                   <div key={idx} className="bg-white dark:bg-stone-900 border border-stone-200 dark:border-stone-800 rounded-xl p-6 shadow-sm">
                                       <h3 className="text-base font-bold text-stone-900 dark:text-white mb-4 flex items-center gap-2">
                                           <span className="w-6 h-6 rounded-full bg-stone-100 dark:bg-stone-800 text-stone-500 flex items-center justify-center text-xs">{idx + 1}</span>
                                           {reel.title}
                                       </h3>
                                       
                                       {reel.keyConcept && (
                                           <div className="mb-4 p-4 bg-orange-50 dark:bg-orange-900/10 rounded-lg border-l-4 border-orange-500">
                                               <span className="text-[10px] font-bold text-orange-600 uppercase tracking-widest block mb-1">Core Concept</span>
                                               <p className="text-sm md:text-base font-medium text-stone-800 dark:text-stone-200 font-serif italic">{reel.keyConcept}</p>
                                           </div>
                                       )}

                                       {reel.bulletPoints && reel.bulletPoints.length > 0 ? (
                                            <ul className="space-y-2 mb-4">
                                                {reel.bulletPoints.map((bp, i) => (
                                                    <li key={i} className="flex gap-2 text-sm text-stone-600 dark:text-stone-400">
                                                        <span className="text-orange-500 mt-1">•</span>
                                                        <span>{bp}</span>
                                                    </li>
                                                ))}
                                            </ul>
                                       ) : (
                                            <p className="text-xs text-stone-400 italic">No detailed notes available.</p>
                                       )}
                                       
                                       <div className="pt-4 border-t border-stone-100 dark:border-stone-800">
                                           <button 
                                                onClick={() => window.open(`https://www.youtube.com/results?search_query=${encodeURIComponent(reel.youtubeQuery || reel.title)}`, '_blank')}
                                                className="text-xs font-bold text-stone-500 hover:text-red-500 uppercase tracking-widest flex items-center gap-1 transition-colors"
                                            >
                                                <span className="material-symbols-outlined text-sm">open_in_new</span>
                                                Related Video Resources
                                            </button>
                                       </div>
                                   </div>
                               ))}
                           </div>
                      </div>
                  )}

                  {activeTab === 'EXAM' && (
                      <div className="space-y-6 animate-fade-in">
                           <div className="mb-6 bg-gradient-to-r from-stone-900 to-stone-800 dark:from-stone-800 dark:to-stone-900 text-white p-8 rounded-2xl relative overflow-hidden">
                               <div className="relative z-10">
                                   <h2 className="text-2xl font-bold font-display mb-2">Exam Preparation Room</h2>
                                   <p className="text-stone-300 text-sm mb-6 max-w-lg">
                                       Enter a distraction-free environment to test your knowledge with AI-generated mock exams based on your syllabus.
                                   </p>
                                   <button 
                                      onClick={onStartExam}
                                      className="px-8 py-4 bg-orange-600 text-white font-bold uppercase tracking-widest text-xs rounded-full hover:bg-orange-700 transition-all shadow-lg flex items-center gap-2 w-fit"
                                   >
                                       Enter Exam Hall
                                       <span className="material-symbols-outlined">arrow_forward</span>
                                   </button>
                               </div>
                               <span className="material-symbols-outlined absolute right-[-20px] bottom-[-20px] text-9xl text-white opacity-5">quiz</span>
                           </div>

                           <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                               <div className="p-6 bg-white dark:bg-stone-900 border border-stone-200 dark:border-stone-800 rounded-xl">
                                    <h3 className="text-sm font-bold text-stone-900 dark:text-white mb-2">Topic Coverage</h3>
                                    <p className="text-xs text-stone-500 mb-4">Questions will be distributed across all generated modules.</p>
                                    <div className="flex gap-2 flex-wrap">
                                        {course.reels.slice(0, 5).map((r, i) => (
                                            <span key={i} className="px-2 py-1 bg-stone-100 dark:bg-stone-800 text-[10px] font-bold uppercase tracking-widest text-stone-500 rounded">{r.title.substring(0, 15)}...</span>
                                        ))}
                                    </div>
                               </div>
                               <div className="p-6 bg-white dark:bg-stone-900 border border-stone-200 dark:border-stone-800 rounded-xl">
                                    <h3 className="text-sm font-bold text-stone-900 dark:text-white mb-2">Exam Rules</h3>
                                    <ul className="space-y-2">
                                        <li className="flex items-center gap-2 text-xs text-stone-500"><span className="material-symbols-outlined text-sm">timer</span> Timed assessment</li>
                                        <li className="flex items-center gap-2 text-xs text-stone-500"><span className="material-symbols-outlined text-sm">block</span> No backtracking</li>
                                        <li className="flex items-center gap-2 text-xs text-stone-500"><span className="material-symbols-outlined text-sm">analytics</span> Instant report card</li>
                                    </ul>
                               </div>
                           </div>
                      </div>
                  )}

              </div>
          </div>
      </div>

    </div>
  );
};

export default ClassroomView;