
import React from 'react';

interface TermsViewProps {
  onBack: () => void;
}

const TermsView: React.FC<TermsViewProps> = ({ onBack }) => {
  return (
    <div className="fixed inset-0 w-full h-[100dvh] bg-[#FAFAFA] dark:bg-[#000000] font-sans text-[#1D1D1F] dark:text-[#F5F5F7] z-50 overflow-y-auto">
       <div className="sticky top-0 w-full p-6 flex justify-end z-50 pointer-events-none">
          <button 
              onClick={onBack} 
              className="pointer-events-auto w-10 h-10 rounded-full bg-stone-200 dark:bg-stone-800 flex items-center justify-center hover:scale-110 transition-transform"
          >
              <span className="material-symbols-rounded">close</span>
          </button>
      </div>

      <div className="max-w-4xl mx-auto px-6 pb-20 animate-fade-in">
          <h1 className="text-4xl md:text-5xl font-bold font-display mb-10">Terms of Service</h1>
          
          <div className="space-y-8 text-stone-600 dark:text-stone-300 leading-relaxed text-sm md:text-base">
              <section>
                  <h3 className="text-stone-900 dark:text-white font-bold text-lg mb-2">1. Acceptance of Terms</h3>
                  <p>By accessing or using Orbis ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Platform.</p>
              </section>

              <section>
                  <h3 className="text-stone-900 dark:text-white font-bold text-lg mb-2">2. Description of Service</h3>
                  <p>Orbis is an AI-powered educational platform that converts text and syllabi into video courses, provides tutoring, and semester planning tools. We utilize advanced artificial intelligence models to generate content.</p>
              </section>

              <section>
                  <h3 className="text-stone-900 dark:text-white font-bold text-lg mb-2">3. User Accounts</h3>
                  <p>You may need to create an account to access certain features. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</p>
              </section>

              <section>
                  <h3 className="text-stone-900 dark:text-white font-bold text-lg mb-2">4. AI Disclaimer</h3>
                  <p>The content generated by Orbis is created by artificial intelligence. While we strive for accuracy, AI can make errors. Educational content provided should be used as a study aid and not as the sole source of truth for academic or professional purposes. Orbis is not liable for any inaccuracies in the generated content.</p>
              </section>

              <section>
                  <h3 className="text-stone-900 dark:text-white font-bold text-lg mb-2">5. Intellectual Property</h3>
                  <p>Content you upload remains yours. Content generated by the platform for your specific use is licensed to you for personal, non-commercial educational use. The underlying technology, design, and software of Orbis remain the exclusive property of Orbis Inc.</p>
              </section>

              <section>
                  <h3 className="text-stone-900 dark:text-white font-bold text-lg mb-2">6. Limitation of Liability</h3>
                  <p>To the fullest extent permitted by law, Orbis shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly.</p>
              </section>

              <section>
                  <h3 className="text-stone-900 dark:text-white font-bold text-lg mb-2">7. Changes to Terms</h3>
                  <p>We reserve the right to modify these terms at any time. We will notify users of any significant changes. Your continued use of the service constitutes acceptance of the new terms.</p>
              </section>

              <section>
                  <h3 className="text-stone-900 dark:text-white font-bold text-lg mb-2">8. Contact</h3>
                  <p>For any questions regarding these terms, please contact us at support@onorbis.com.</p>
              </section>
              
              <p className="text-xs text-stone-400 mt-12 pt-12 border-t border-stone-200 dark:border-stone-800">
                  Last Updated: October 2023
              </p>
          </div>
      </div>
    </div>
  );
};

export default TermsView;
